name: get_uploader_app

on:
  push:
    branches:
      - main
    paths:
      - uploader_target_version.txt



jobs:
  read_version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/read-first-line.yml
    with:
      FILE_NAME: uploader_target_version.txt

