name: get_uploader_app

on:
  push:
    branches:
      - main
    paths:
      - uploader_target_version.txt



jobs:
  read_version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/read-first-line.yml
    with:
      FILE_NAME: uploader_target_version.txt
  download_uploader:
    needs:
    - read_version
    uses: dsaltares/fetch-gh-release-asset@master
    with:
      repo: 'cll023/test_release_uploader_app'
      version: 'tags/v0.0.01'
      regex: true
      file: "*"
      target: 'uploader/'
      token: ${{ secrets.GITHUB_TOKEN }}
